SELECT TRAIN_NO,
RUN_ORDR,
STATION_NM,
LEAD(STATION_NM) OVER (PARTITION BY TRAIN_NO
ORDER BY RUN_ORDR) AS "다음 역명"
FROM TB_TRAIN_TM;
SELECT TRAIN_NO,
RUN_ORDR,
STATION_NM,
LAG(STATION_NM) OVER (PARTITION BY TRAIN_NO
ORDER BY RUN_ORDR) AS "이전 역명"
FROM TB_TRAIN_TM;
SELECT TRAIN_NO,
SUBSTR(XMLAGG(XMLELEMENT(X, ',', STATION_NM)
ORDER BY RUN_ORDR).EXTRACT('//text()'),2) AS 역목록
FROM TB_TRAIN_TM
GROUP BY TRAIN_NO;
SELECT TRAIN_NO,
SUBSTR(XMLAGG(XMLELEMENT(X, ',', STATION_NM || '(' ||
ARV_TM || ')') ORDER BY RUN_ORDR).EXTRACT('//text()'),2)
FROM TB_TRAIN_TM
GROUP BY TRAIN_NO;